Task.MVC/Models/ErrorViewModel.cs
namespace Task.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Task.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Task.Models;

namespace Task.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

Task.MVC/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using Task.BLL.Interfaces;

namespace Task.Controllers;

public class MessageController : Controller
{
    private readonly IRabbitMqService _rabbitMqService;

    public MessageController(IRabbitMqService rabbitMqService)
    {
        _rabbitMqService = rabbitMqService;
    }

    public IActionResult Index()
    {
        const string queueName = "test-queue";
        const string message = "Hello, RabbitMQ!";
        _rabbitMqService.SendMessage(queueName, message);

        return View();
    }
}

Task.MVC/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Task.BLL.DTO;
using Task.BLL.Interfaces;

namespace Task.Controllers;

public class OrdersController : Controller
    {
        private readonly IEntityService<OrdersDto> _orderService;

        public OrdersController(IEntityService<OrdersDto> orderService)
        {
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var orders = _orderService.GetAll();
            return View(orders);
        }

        public IActionResult Details(int id)
        {
            var order = _orderService.GetById(id);

            return View(order);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(OrdersDto orderDto)
        {
            if (ModelState.IsValid)
            {
                _orderService.Create(orderDto);
                return RedirectToAction(nameof(Index));
            }

            return View(orderDto);
        }

        public IActionResult Edit(int id)
        {
            var order = _orderService.GetById(id);

            return View(order);
        }

        [HttpPost]
        public IActionResult Edit(int id, OrdersDto orderDto)
        {
            if (id != orderDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _orderService.Update(orderDto);
                return RedirectToAction(nameof(Index));
            }

            return View(orderDto);
        }

        public IActionResult Delete(int id)
        {
            var order = _orderService.GetById(id);

            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _orderService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteConfirmed()
        {
            throw new NotImplementedException();
        }
    }

Task.MVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Task.BLL.DTO;
using Task.BLL.Interfaces;

namespace Task.Controllers;

public class UsersController : Controller
    {
        private readonly IEntityService<UsersDto> _userService;

        public UsersController(IEntityService<UsersDto> userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            var users = _userService.GetAll();
            return View(users);
        }

        public IActionResult Details(int id)
        {
            var user = _userService.GetById(id);

            return View(user);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(UsersDto userDto)
        {
            if (ModelState.IsValid)
            {
                _userService.Create(userDto);
                return RedirectToAction(nameof(Index));
            }

            return View(userDto);
        }

        public IActionResult Edit(int id)
        {
            var user = _userService.GetById(id);

            return View(user);
        }

        [HttpPost]
        public IActionResult Edit(int id, UsersDto userDto)
        {
            if (id != userDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _userService.Update(userDto);
                return RedirectToAction(nameof(Index));
            }

            return View(userDto);
        }

        public IActionResult Delete(int id)
        {
            var user = _userService.GetById(id);

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _userService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteConfirmed()
        {
            throw new NotImplementedException();
        }
    }

Task.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Task.MVC/Views/Message/Index.cshtml
@{
    ViewData["Title"] = "SendMessageToRabbitMQ";
}

<h2>Send Message to RabbitMQ</h2>

<form method="post" action="@Url.Action("Index")">
    <button type="submit" class="btn btn-primary">Send Message</button>
</form>

Task.MVC/Views/Orders/Create.cshtml
@using OrdersDto = Task.BLL.DTO.OrdersDto
@model OrdersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create New Order</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="UserId">User ID:</label>
        <input asp-for="UserId" class="form-control" />
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<a asp-action="Index">Back to List</a>

Task.MVC/Views/Orders/Delete.cshtml
@using OrdersDto = Task.BLL.DTO.OrdersDto
@model OrdersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Delete Order</h2>

<div>
    <h4>Order Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID:</dt>
        <dd class="col-sm-10">@Model.Id</dd>

        <dt class="col-sm-2">User ID:</dt>
        <dd class="col-sm-10">@Model.UserId</dd>

        <dt class="col-sm-2">Price:</dt>
        <dd class="col-sm-10">@Model.Price</dd>
    </dl>
</div>

<form asp-action="DeleteConfirmed" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </div>
</form>

Task.MVC/Views/Orders/Details.cshtml
@using OrdersDto = Task.BLL.DTO.OrdersDto
@model OrdersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Order Details</h2>

<div>
    <h4>Order Info</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID:</dt>
        <dd class="col-sm-10">@Model.Id</dd>

        <dt class="col-sm-2">User ID:</dt>
        <dd class="col-sm-10">@Model.UserId</dd>

        <dt class="col-sm-2">Price:</dt>
        <dd class="col-sm-10">@Model.Price</dd>
    </dl>
</div>
<p>
    <a asp-action="Index">Back to List</a>
</p>

Task.MVC/Views/Orders/Edit.cshtml
@using OrdersDto = Task.BLL.DTO.OrdersDto
@model OrdersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit Order</h2>

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="UserId">User ID:</label>
        <input asp-for="UserId" class="form-control" />
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price">Price:</label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<a asp-action="Index">Back to List</a>

Task.MVC/Views/Orders/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Orders List</h2>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>User ID</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var order in Model)
    {
        <tr>
            <td>@order.Id</td>
            <td>@order.UserId</td>
            <td>@order.Price</td>
            <td>
                <a asp-action="Details" asp-route-id="@order.Id">Details</a> |
                <a asp-action="Edit" asp-route-id="@order.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@order.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="Create">Create New</a>

Task.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Task.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Task.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task.MVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">RabbitMQ</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Task.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Task.MVC/Views/Users/Create.cshtml
@using UsersDto = Task.BLL.DTO.UsersDto
@model UsersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create User</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Surname">Surname:</label>
        <input asp-for="Surname" class="form-control" />
    </div>
    
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    
    <div class="form-group">
        <label asp-for="Middlename">Middlename:</label>
        <input asp-for="Middlename" class="form-control" />
    </div>
    
    <div class="form-group">
        <label asp-for="Birthday">Birthday:</label>
        <input asp-for="Birthday" class="form-control" />
    </div>
    
    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index">Back to List</a>
</form>

Task.MVC/Views/Users/Delete.cshtml
@using UsersDto = Task.BLL.DTO.UsersDto
@model UsersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Delete User</h2>

<div>
    <h4>User Info</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID:</dt>
        <dd class="col-sm-10">@Model.Id</dd>

        <dt class="col-sm-2">Surname:</dt>
        <dd class="col-sm-10">@Model.Surname</dd>

        <dt class="col-sm-2">Name:</dt>
        <dd class="col-sm-10">@Model.Name</dd>

        <dt class="col-sm-2">Middlename:</dt>
        <dd class="col-sm-10">@Model.Middlename</dd>

        <dt class="col-sm-2">Birthday:</dt>
        <dd class="col-sm-10">@Model.Birthday.ToShortDateString()</dd>
    </dl>
</div>
<form asp-action="DeleteConfirmed">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </div>
</form>

Task.MVC/Views/Users/Details.cshtml
@using UsersDto = Task.BLL.DTO.UsersDto
@model UsersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>User Details</h2>

<div>
    <h4>User Info</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID:</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        
        <dt class="col-sm-2">Surname:</dt>
        <dd class="col-sm-10">@Model.Surname</dd>
        
        <dt class="col-sm-2">Name:</dt>
        <dd class="col-sm-10">@Model.Name</dd>
        
        <dt class="col-sm-2">Middlename:</dt>
        <dd class="col-sm-10">@Model.Middlename</dd>
        
        <dt class="col-sm-2">Birthday:</dt>
        <dd class="col-sm-10">@Model.Birthday.ToShortDateString()</dd>
    </dl>
</div>
<p>
    <a asp-action="Index">Back to List</a>
</p>

Task.MVC/Views/Users/Edit.cshtml
@using UsersDto = Task.BLL.DTO.UsersDto
@model UsersDto

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit User</h2>

<form asp-action="Edit">
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
        <label asp-for="Surname" class="control-label"></label>
        <input asp-for="Surname" class="form-control" />
        <span asp-validation-for="Surname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Middlename" class="control-label"></label>
        <input asp-for="Middlename" class="form-control" />
        <span asp-validation-for="Middlename" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Birthday" class="control-label"></label>
        <input asp-for="Birthday" class="form-control" />
        <span asp-validation-for="Birthday" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

Task.MVC/Views/Users/Index.cshtml
<h2>User List</h2>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Surname</th>
        <th>Name</th>
        <th>Middlename</th>
        <th>Birthday</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Id</td>
            <td>@user.Surname</td>
            <td>@user.Name</td>
            <td>@user.Middlename</td>
            <td>@user.Birthday.ToShortDateString()</td>
            <td>
                <a asp-action="Details" asp-route-id="@user.Id">Details</a> |
                <a asp-action="Edit" asp-route-id="@user.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@user.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="Create">Create New</a>